# Changelog: https://developers.google.com/tag-platform/tag-manager/server-side/release-notes
# Image repository: https://console.cloud.google.com/gcr/images/cloud-tagging-10302018/global/gtm-cloud-image
FROM gcr.io/cloud-tagging-10302018/gtm-cloud-image:2.1.0
