name-template: 'v$MAJOR.$MINOR.$PATCH 🌈'
tag-template: 'v$MAJOR.$MINOR.$PATCH'

version-template: '$MAJOR.$MINOR.$PATCH'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Hot fix'
    label: 'hotfix'
  - title: '🧺 Miscellaneous' #Everything except ABAP
    label: 'misc'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'feature'
  minor:
    labels:
      - 'bugfix'
      - 'fix'
  patch:
    labels:
      - 'hotfix'
  default: patch
  
template: |
  ## Changes
  $CHANGES
