name-template: "v{{ version }}"
tag-template: "{{ version }}"
categories:
  - title: "Features"
    label: "feature"
  - title: "Bug Fixes"
    label: "bug"
  - title: "Enhancements"
    label: "enhancement"
  - title: "Documentation"
    label: "documentation"

template: |
  # Release Notes {{ version }}

  {{#each categories}}
  ## {{ this.title }}
  {{#each changes}}
  {{#ifCond this.labels.[0] '===' ../this.label}}
  - {{ this.title }}
  {{/ifCond}}
  {{/each}}
  {{/each}}

footer: "Thank you for using our software!"
