name: Automatic Labeler

on:
  issues:
    types:
      - opened

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            {"bug": ["bug", "fix"], "feature": ["feature"], "hotfix": ["hotfix"]}
