name: Publish Release

on:
  workflow_run:
    workflows: ["Release Drafter"]
    types:
      - completed

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            my-artifact.zip  # Add other files as needed
          title: Release Title
          body: Release Description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
