name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - release

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch PRs and Commit Messages
      id: fetch_prs_and_commit_messages
      run: |
        git fetch origin +refs/pull/*/merge:refs/remotes/origin/pr/*
        git for-each-ref --format='%(refname:short)' refs/remotes/origin/pr > prs.txt

        while read -r pr; do
          git log --pretty=format:"- %s @%an (#$pr)" "pr/$pr" >> commit_messages.txt
        done < prs.txt

    - name: Create Draft Release
      id: create_release
      uses: release-drafter/release-drafter@v5
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          additional-files: commit_messages.txt
          commit-message: true
