name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - release

jobs:
  update_release_draft:
    runs-on: [self-hosted, Linux, size/small, emt]
    steps:
      - name: Set GHE_HOST
        run: |
         echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}