name: Generate Release Notes

on:
  pull_request:
    types: [closed]
  push:
    branches:
        - release
jobs:
  generate_release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Fetch draft release
        id: draft_release
        run: |
          draft_tag=$(curl -sH "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[] | select(.draft) | .tag_name')
          echo "DRAFT_RELEASE_TAG_NUMBER=$draft_tag" >> $GITHUB_ENV

      - name: Set draft release tag output
        id: set_draft_release_tag
        run: echo "::set-output name=DRAFT_RELEASE_TAG_NUMBER::$DRAFT_RELEASE_TAG_NUMBER"

      - name: Run script
        run: python .github/scripts/generate-release-notes.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
